### ISSUE TITLE
Kullanıcı adı ve şifre hatası

### ISSUE THREAD

**Issue by harmancode** [mirzazeyrek/toplu-entry-sildirgeci#1]
Uygulamada bir sorun mu var acaba? Zira kullanıcı adı (e-posta) ve şifreyi doğru girmekteyim.

**Comment by mirzazeyrek** [comment]
selam,

tasarımı değiştirdiler. login olup olmadığını kontrol eden fonksiyon şu anda doğru işlemiyor olabilir.

**Comment by harmancode** [comment]
kontrol edebilirseniz, düzeltebilirseniz çok sevinirim. bu ara özellikle ihtiyaç var bu uygulamaya. :)

**Comment by Mytonn** [comment]
Merhaba, sırf yorum yapabilmek için üye oldum :) Ben de sizden düzeltmeyi yapmanız konusunda ricada bulunmak istiyorum. Zaman ayırabilirseniz çok makbule geçecek..

**Comment by mirzazeyrek** [comment]
@dx486 @Mytonn 

scripti güncelledim*. şu anda yavaş da olsa çalışıyor. ilk yazdığımda 5-10 dk içinde 4 bin entry'i silebilmiştim. şimdi nedense teknik sebeplerle dakikada 2 entry silme limiti geldi!

*düzeltme değil güncelleme diyorum özellikle çünkü bozukluk ya da hata yoktu uygulamada. tasarım değişince miadını doldurma (outdated olma) durumuydu.

**Comment by mirzazeyrek** [comment]
konu kilit.
